### PR TITLE
MulticastService optimizations

### PR DESCRIPTION
**Pull request by eshvatskyi**
- fixed AnswersContainsAdditionalRecords functionality
 - fixed using MulticastService with multiple NICs
 - removed exploring networks by timers instead used NetworkChange.NetworkAddressChanged

### CODE REVIEW

**Comment by richardschneider** [comment]
It appears that this PR is not based on the latest bits. The [recently sent logic](https://github.com/richardschneider/net-mdns/commit/1d6ae4349435dc8c6fdef2e221e33c4d5864b276) has been removed!

You will need to [rebase](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) the PR.

**Comment by richardschneider** [comment]
@eshvatskyi Good find on `NetworkChangedEvent`.  Is it raised when the laptop wakes up from a sleep?

**Comment by eshvatskyi** [comment]
> @eshvatskyi Good find on `NetworkChangedEvent`. Is it raised when the laptop wakes up from a sleep?

yes, it is

**Comment by eshvatskyi** [comment]
> It appears that this PR is not based on the latest bits. The [recently sent logic](https://github.com/richardschneider/net-mdns/commit/1d6ae4349435dc8c6fdef2e221e33c4d5864b276) has been removed!
> 
> You will need to [rebase](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) the PR.

done. Also please check GetIPAddresses method, looks like it should be default return only InterNetwork adressses

**Comment by eshvatskyi** [comment]
@richardschneider I've tried to fix all timeout issues from test, but looks like this is non windows specific issues. Please let me know if you can go thought with me

**Comment by richardschneider** [comment]
Lots of issues here.  I especially don't like breaking the Interface (removing IDisposable) and changing all tests.  This means all dependent packages are **broken**.

I feel that maintaining multiple senders is wrong.  Multiple NICs are already suppported (see #15 and #12).  If you disagree, please raise an issue describing the problem.

I suggest that you proceeded by creating two new PRs
- fix `AnswersContainsAdditionalRecords` functionality
- use `NetworkAddressChanged` event

I do appreciate the work you are doing.  Please continue.

**Comment by eshvatskyi** [comment]
np, but it's not working with multiple nic as expected.
when you sending query it's not sent to all subnets, but to first suitable.
sender.MulticastLoopback = true;
I dont nkow why this is used, this is actually duplicated query to loopback (good for testing not useful in subnets)

**Comment by richardschneider** [comment]
> sender.MulticastLoopback = true;
I dont nkow why this is used, this is actually duplicated query to loopback (good for testing not useful in subnets)

`MulticastLoopback` has nothing to do with the loopback interface.  It allows a sender to also receive its sent message. See the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.multicastloopback?view=netframework-4.7.2),  A big feature of mDNS is passive monitoring of messages.  With loopback, the sending app can respond to its own query without having to write special code to deal with a query from itsself or another.

**Pull request closed without merging**
